sources: 
  - name: raw
    database: "{{ env_var('GCP_PROJECT') }}"
    schema: raw
    tables:
      - name: personas
        description: "table with the demographic information of the borrower"
      - name: cuentas
        description: "table with the information of the accounts of the borrower"
      - name: domicilios
        description: "table with the information of the addresses of the borrower"
      - name: consultas
        description: "table with the information of the credit inquiries of the borrower"
      - name: applications
        description: "table with the information of the credit applications of the borrower"